name: Build MCP Server Base Docker Image

on:
  workflow_call:
    inputs:
      push_to_gcr:
        description: "Whether to push the built image to GCR"
        required: true
        type: boolean
      version:
        description: "Version tag for the Docker image"
        required: true
        type: string
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER:
        required: false
      GCP_SERVICE_ACCOUNT_NAME:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Authenticate to Google Cloud
        if: inputs.push_to_gcr
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER }}

      - name: Set up Google Cloud
        if: inputs.push_to_gcr
        uses: google-github-actions/setup-gcloud@7252237d1753f6304a1df72e928171a1a0be20f5 # v2.1.2

      - name: Configure Docker for Artifact Registry
        if: inputs.push_to_gcr
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: ./mcp_server_docker_image
          file: ./mcp_server_docker_image/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push_to_gcr }}
          tags: |
            europe-west1-docker.pkg.dev/friendly-path-465518-r6/archestra/mcp-server-base:${{ inputs.version }}
            europe-west1-docker.pkg.dev/friendly-path-465518-r6/archestra/mcp-server-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
