name: Build MCP Server Base Docker Image

on:
  workflow_call:
    inputs:
      push_to_gcr:
        description: "Whether to push the built image to GCR"
        required: true
        type: boolean
      version:
        description: "Version tag for the Docker image"
        required: true
        type: string
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER:
        required: false
      GCP_SERVICE_ACCOUNT_NAME:
        required: false

jobs:
  build-base-mcp-server-docker-image:
    name: Build MCP Server Base Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Authenticate to Google Cloud
        if: inputs.push_to_gcr == 'true'
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER }}

      - name: Set up Google Cloud
        if: inputs.push_to_gcr == 'true'
        uses: google-github-actions/setup-gcloud@6a7c903a70c8625ed6700fa299f5ddb4ca6022e9 # v2.1.5

      - name: Configure Docker for Artifact Registry
        if: inputs.push_to_gcr == 'true'
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./mcp_server_docker_image
          file: ./mcp_server_docker_image/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push_to_gcr == 'true' }}
          tags: |
            europe-west1-docker.pkg.dev/friendly-path-465518-r6/archestra-public/mcp-server-base:${{ inputs.version }}
            europe-west1-docker.pkg.dev/friendly-path-465518-r6/archestra-public/mcp-server-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
