name: Linting and Tests

on:
  workflow_call:

jobs:
  lint-pr-title:
    name: PR Title Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Lint PR title
        uses: grafana/shared-workflows/actions/lint-pr-title@19d8fb5687bb386849f7f53673c5f429e6387cf5 # v1.2.0
        with:
          config-path: "${{ github.workspace }}/.github/commitlint.config.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  desktop-app-linting-and-tests:
    name: Desktop App Linting and Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./desktop_app
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Check prettier formatting
        run: pnpm prettier --check .

      - name: Run tests
        run: pnpm test

      # TODO: add this later
      # - name: Build
      #   run: pnpm make

  verify-codegend-code-is-up-to-date:
    name: Verify generated code is up to date
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./desktop_app
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Codegen
        run: pnpm codegen:all

      - name: Check for changes and commit if needed
        run: |
          # Check both unstaged and staged changes
          if ! git diff --exit-code || ! git diff --cached --exit-code; then
            git add .
            git commit -m "chore: update generated code"
            git push --no-verify
          fi

  zizmor:
    name: Zizmor GitHub Actions static analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@f52a838cfabf134edcbaa7c8b3677dde20045018 # v0.1.1

  build-mcp-server-base-image:
    name: Build MCP Server Base Docker Image
    uses: ./.github/workflows/build-base-mcp-server-docker-image.yml
    with:
      push_to_gcr: false
      version: ${{ github.sha }}
    secrets: inherit
