# TODO: remove this when done testing
name: On commits to main

on:
  push:
    # branches:
    #   - main

jobs:
  build-mcp-server-base-image:
    name: Build MCP Server Base Docker Image
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    uses: ./.github/workflows/build-base-mcp-server-docker-image.yml
    with:
      push_to_gcr: true
      version: 0.0.1
    secrets:
      GCP_SERVICE_ACCOUNT_NAME: ${{ secrets.DEVELOPMENT_OAUTH_PROXY_RELEASER_GCP_SERVICE_ACCOUNT_NAME }}
      GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER: ${{ secrets.DEVELOPMENT_OAUTH_PROXY_RELEASER_GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER }}
