name: On commits to main

on:
  push:
    # TODO: uncomment this out when done testing
    # branches:
    #   - main
    # paths:
    #   # To run this workflow on all commits to main, remove the paths filter below
    #   - "oauth-proxy/**"
    #   - ".github/workflows/deploy-oauth-proxy-server-to-cloud-run.yml"
    #   - ".github/workflows/on-commits-to-main.yml"

concurrency:
  group: on-commits-to-main
  cancel-in-progress: true

jobs:
  deploy-oauth-proxy-to-dev:
    name: Deploy OAuth Proxy to Dev
    uses: ./.github/workflows/deploy-oauth-proxy-server-to-cloud-run.yml
    permissions:
      contents: read
      id-token: write  # Required for Workload Identity Federation
    with:
      environment: development
      version: ${{ github.sha }}
      redirect_uri: https://oauth.dev.archestra.ai
    secrets:
      GCP_PROJECT_ID: ${{ secrets.DEVELOPMENT_GCP_PROJECT_ID }}
      GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER: ${{ secrets.DEVELOPMENT_OAUTH_PROXY_RELEASER_GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER }}
      GCP_SERVICE_ACCOUNT_NAME: ${{ secrets.DEVELOPMENT_OAUTH_PROXY_RELEASER_GCP_SERVICE_ACCOUNT_NAME }}
