name: On Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "on-pull-requests-${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  linting-and-tests:
    name: Linting and Tests
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/linting-and-tests.yml
